---
- import_playbook: ./update.yml
- import_playbook: ./volumes.yml
- import_playbook: ./samba.yml
- import_playbook: ./docker.yml
- import_playbook: ./docker-watchdog.yml
- import_playbook: ./nginx.yml
- import_playbook: ./ssh.yml
- import_playbook: ./ufw.yml
- import_playbook: ./qbittorrent.yml
- import_playbook: ./filebrowser.yml
- import_playbook: ./backup.yml
- import_playbook: ./monitoring.yml
- import_playbook: ./portainer.yml
